# @baseUrl = http://localhost:3001
@baseUrl = http://62.238.6.62:3001

### List all available groups
GET {{baseUrl}}/schedule/groups

### List all lecturers
GET {{baseUrl}}/schedule/lecturers

### Full schedule (all sections)
GET {{baseUrl}}/schedule

### Schedule for a specific group (replace with actual group id from /groups)
GET {{baseUrl}}/schedule/group/31_2

### Schedule for string group (II stopien)
GET {{baseUrl}}/schedule/group/CY1

### Schedule for lecturer by abbreviation
GET {{baseUrl}}/schedule/lecturer/JW.
